### ISSUE TITLE
#ITEM 1- Implement Savas & Koç Montgomery modular inverse algorithm

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-corretto#14]
This issue is under the item: https://gitlab.dusk.network/dusk-org/tech/issues/1.

The goal is to implement:
Montgomery inversion - Erkay Sava ̧s & Çetin Kaya Koç
J Cryptogr Eng (2018) 8:201–210
https://doi.org/10.1007/s13389-017-0161-x

And benchmark the algo vs. Kalinski's one implemented on #9 .

Addition chais are probably a higher performance solution. Maybe @Bounce23 can bring some light researching a bit.

**Comment by Bounce23** [comment]
One thing to bear in mind is that we can use the hardcoded addition chain for the inversion algorithm. The spending for the operations acts as exactly doubling each operation so this can benchmarked against the other two. 
The chain template can be found in `field.rs` of the dalek repo.

**Comment by CPerezz** [comment]
But is it the same? Applies on the same way¿? Or something should be refactored? 
I ask that since the prime of the field isn't the same.

PS: You refer to [this](https://github.com/dalek-cryptography/curve25519-dalek/blob/f630041af28e9a405255f98a8a93adca18e4315b/src/field.rs#L175) right?

**Comment by Bounce23** [comment]
Yes, you are correct. The need to refactor is why I used the word 'template'.

**Comment by Bounce23** [comment]
Yes, you are correct. The need to refactor is why I used the word 'template'.

**Comment by CPerezz** [comment]
As mentioned on last commits this will remain closed until addition chain implementations are found or discarded.

**Comment by Bounce23** [comment]
The optimum method of Modular inverse was always this algorithm as using addition chains required defining all of the temporary t value field elements up to and including 2^260.  
The tenacity towards a working Kalinsky has paid off as we now have a working implementation of the Kavas and Koç Algorithm for modular inverse. Therefore, this issue can be reopened and the whole modular inverse will be completed in the next 36 hours.
