### ISSUE TITLE
#ITEM 1 - Review Phase 1 of Kalinski's algorithm.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-corretto#15]
Since the algorithm implemented on #9 was passing the tests, we thought that `Phase I ` was working correctly.

But while working on #14 we realized the function only works for the tested value surprisingly ..

So now it's time to find the bug that it's affecting `Phase I` of the Kalinski's algorithm.

**Comment by CPerezz** [comment]
Phase I is working correctly working now since the tests performed by @Bounce23 and me in 035777b. 

But an error has appeared on the Phase II while we perform the addition for `rr + p` since it should give an even number but gives an odd one.
Due to this. `half()` function does not do the job correctly since it's dividing odd numbers and the decimals should be rounded, not truncated.
Will open a new issue for it.

**Comment by CPerezz** [comment]
Reopened since errors still appearing on the implementation.
They were found on: 638a41f

**Comment by Bounce23** [comment]
Errors are seemingly inexplicable. Alongside this, there is no working example of the Kalinski algorithm, nor any means to contact him. I will build an inversion on double chain addition for use instead. Although this is relatively more difficult than the Algorithm, it WILL work and it provides us with constant time operations, meaning no need for later optimisation in that regard.

**Comment by CPerezz** [comment]
As mentioned on last commits this will remain closed until addition chain implementations are found or discarded.

**Comment by Bounce23** [comment]
The optimum method of Modular inverse was always this algorithm as using addition chains required defining all of the temporary t value field elements up to and including 2^260.  
The tenacity towards a working Kalinsky has paid off as we now have a working implementation of the Kavas and Koç Algorithm for modular inverse. Therefore, this issue can be reopened and the whole modular inverse will be completed in the next 36 hours.
