### ISSUE TITLE
#ITEM 1 - Solve addition for FIELD_L on Phase II.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-corretto#17]
This issue is under the item: https://gitlab.dusk.network/dusk-org/tech/issues/1.

This issue comes from #15 solution while checking the correctness of #12 implementing the Savas & Koç algorithm in #14 .

An error has appeared on the Phase II algorithm while we performing the addition: `rr + p` since it should give an even number but gives an odd one.
Due to this, `half()` function does not do the job correctly since it's dividing odd numbers and the decimals should be rounded, not truncated.

**Comment by CPerezz** [comment]
Found that Phase I stills failing, it only works for multiples of one test value.

Also point out that one implementation error on the return statement was found & solved on: 638a41f
This will make us re-open #15

**Comment by CPerezz** [comment]
As mentioned on last commits this will remain closed until addition chain implementations are found or discarded.

**Comment by Bounce23** [comment]
The optimum method of Modular inverse was always this algorithm as using addition chains required defining all of the temporary t value field elements up to and including 2^260.  
The tenacity towards a working Kalinsky has paid off as we now have a working implementation of the Kavas and Koç Algorithm for modular inverse. Therefore, this issue can be reopened and the whole modular inverse will be completed in the next 36 hours.
