### ISSUE TITLE
#ITEM 1 - Implement point addition for Doppio.

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/dusk-corretto#8]
This issue lives under the item: https://gitlab.dusk.network/dusk-org/tech/issues/1 and it's one of it's main goals.

We need now to implement point addition operations over the Doppio Curve using Projective Twisted Edwards coordinates.

Found a paper with good performant algorithms to implement them:
[Source: 2008 Hisil–Wong–Carter–Dawson, http://eprint.iacr.org/2008/522, Section 3.1.](http://eprint.iacr.org/2008/522).

The algorithm costs are:
- Cost: 9M + 1*a + 7add.
- Cost: 9M + 1*a + 6add dependent upon the first point.

@Bounce23 mentioned that there are more efficient algorithms but we need to review them. But to at least have something working, the implementation of the algorithm mentioned above has been started on b45abc5

**Comment by Bounce23** [comment]
Following todays work and then review of previous implementation of projective coordinates, it follows the we will be using weighted projective coordinates. The chosen algorithm will incur a cost that stated above but for implementing them as parallel operations, the conversions to affine coordinates and `1I + 3M + 1S`.

For the total algorithm cost they vary upon the ability to determine coordinates equalling 0. If found they reduce the overall cost for general point addition by `1S + 1M`.

Note: the need for 0 coordinates is not to be confused with academic paper, shown above, which provides a high speed algorithm assuming that `T = 0`.
